package(default_visibility = ["//visibility:public"])

cc_library(
    name = "base",
    srcs = ["base.cc"],
    hdrs = ["base.h"],
    deps = [
        "//third_party/gflags:gflags-cxx",
        "//third_party/glog:glog-cxx",
    ],
    linkstatic = 1,
    alwayslink= 1,

)

